baseURL = '' 
languageCode = 'en-us'
title = 'The Art of TokenBending'
theme = 'PaperMod'

[menu]

  [[menu.main]]
    identifier = "home"
    name = "home"
    url = "/"

  [[menu.main]]
    identifier = "journal"
    name = "journal"
    url = "/journal/"